USE [master]
GO

/****** Object:  Database [ecomDB]    Script Date: 6/11/2026 10:25:32 AM ******/
CREATE DATABASE [ecomDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ecomDB', FILENAME = N'C:\Users\pcit86\ecomDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ecomDB_log', FILENAME = N'C:\Users\pcit86\ecomDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ecomDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ecomDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ecomDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ecomDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ecomDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ecomDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ecomDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ecomDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ecomDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ecomDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ecomDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ecomDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ecomDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ecomDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ecomDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ecomDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ecomDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ecomDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ecomDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ecomDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ecomDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ecomDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ecomDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ecomDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ecomDB] SET  MULTI_USER 
GO

ALTER DATABASE [ecomDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ecomDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ecomDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ecomDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ecomDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ecomDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ecomDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ecomDB] SET  READ_WRITE 
GO


